apps/services/package.json
apps/services/src/app.ts
apps/services/src/env.ts
apps/services/src/plugins/configuration.ts
apps/services/src/server.ts
apps/services/tsconfig.json
pnpm-lock.yaml
pnpm-workspace.yaml

Add basic initial app backend services

---

apps/services/.env.example
apps/services/package.json
apps/services/src/app.ts
apps/services/src/errors/not-found-error.ts
apps/services/src/plugins/error.ts
apps/services/src/plugins/request-id.ts
pnpm-lock.yaml

add liveness and healthz, add error and request-if configuration

add healthz and liveness, plus structural plugins

---

.gitignore
apps/services/package.json
apps/services/src/model/migrations/wl-ddl_20250528223345.ts
apps/services/src/model/orm.config.ts
apps/services/src/modules/worklist/entities/worklist-column.entity.ts
apps/services/src/modules/worklist/entities/worklist.entity.ts
apps/services/src/modules/worklist/index.ts
apps/services/src/modules/worklist/routes/column-create.ts
apps/services/src/modules/worklist/routes/column-delete.ts
apps/services/src/modules/worklist/routes/column-list.ts
apps/services/src/modules/worklist/routes/column-update.ts
apps/services/src/modules/worklist/routes/create.ts
apps/services/src/modules/worklist/routes/delete.ts
apps/services/src/modules/worklist/routes/get.ts
apps/services/src/modules/worklist/routes/list.ts
apps/services/src/modules/worklist/routes/update.ts
apps/services/src/plugins/orm.ts
apps/services/src/plugins/swagger.ts
pnpm-lock.yaml
pnpm-workspace.yaml

add full worklist and columns api, add model, add plugins to configure app and swagger

feat: 🎸 api

---

apps/app/src/app/(dashboard)/components/WorklistNavigation.tsx
apps/app/src/app/(dashboard)/components/WorklistSortableColumnHeader.tsx
apps/app/src/app/(dashboard)/components/WorklistTable.tsx
apps/app/src/app/(dashboard)/components/WorklistTableRow.tsx
apps/app/src/app/(dashboard)/page.tsx
apps/app/src/app/actions/ai-chat.ts
apps/app/src/app/layout.tsx
apps/app/src/hooks/use-column-creator.ts
apps/app/src/hooks/use-medplum-store.ts
apps/app/src/hooks/use-search.ts
apps/app/src/lib/fhir-path.ts
apps/app/src/types/worklist.ts
apps/app/src/utils/constants.ts

do some cleanup and restructure on the worklist tables, improve search and change the structure of a worklist to contain two different views

refactor: 💡 perform some cleanup in the work lists

---

package.json
pnpm-lock.yaml

chore: 🤖 repo - update turbo

---

.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
apps/app/package.json
apps/services/package.json
apps/services/src/app.ts
apps/services/src/modules/worklist/routes/column-create.ts
apps/services/src/modules/worklist/routes/column-delete.ts
apps/services/src/modules/worklist/routes/column-list.ts
apps/services/src/modules/worklist/routes/column-update.ts
apps/services/src/modules/worklist/routes/create.ts
apps/services/src/modules/worklist/routes/delete.ts
apps/services/src/modules/worklist/routes/get.ts
apps/services/src/modules/worklist/routes/list.ts
apps/services/src/modules/worklist/routes/update.ts
apps/services/src/types.ts
apps/services/test/setup.ts
apps/services/test/worklist-column.test.ts
apps/services/test/worklist.test.ts
apps/services/vitest.config.ts
package.json
pnpm-lock.yaml
turbo.json

fix api return types and schema validation, fix tests shape to reflect schema validation

fix: 🐛 api - to return proper schema shape and validation

---

README.md
package.json
turbo.json

Add root level docs script to start doc site. Update readme toc

docs: ✏️ configuration

---

apps/docs/.vitepress/config.mts

docs: ✏️ pipeline

---

.npmrc.docker
README.md
apps/docs/.vitepress/config.mts
apps/docs/getting-started/environment-setup.md
apps/docs/guides/deployment/deploy-aws.md
apps/docs/guides/deployment/deploy-kubernetes.md
apps/docs/guides/developers/index.md
apps/docs/guides/development/integrate-api.md
apps/docs/guides/development/use-rest-api.md
apps/docs/guides/devops/index.md
apps/docs/guides/end-users/index.md
apps/docs/guides/panels/create-panel.md
apps/docs/index.md
apps/docs/interactive/config-generator.md
apps/services/dockerfile
dev/scripts/README.md
dev/scripts/generate-env.js
dev/scripts/validate-docs.js
package.json
pnpm-lock.yaml

Add documentation for rest api. Add env vars generator. Add services backend docker image file

docs: ✏️ documentation update

---

apps/docs/.vitepress/config.mts

changed base uri for docs to new repo name

chore: 🤖 docs

---

apps/app/src/app/panel/[panel]/components/WorklistColumnMenu.tsx
apps/app/src/app/panel/[panel]/components/WorklistSortableColumnHeader.tsx
apps/app/src/app/panel/[panel]/components/WorklistTable.tsx
apps/app/src/app/panel/[panel]/components/WorklistTableRow.tsx
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/app/panel/[panel]/view/[view]/page.tsx
apps/app/src/types/worklist.ts

remove redudant funcionality, allow space click and fix font size

fix: 🐛 improve filter

---

apps/app/src/app/panel/[panel]/components/ColumnsDropdown.tsx
apps/app/src/app/panel/[panel]/components/WorklistColumnMenu.tsx
apps/app/src/app/panel/[panel]/components/WorklistSortableColumnHeader.tsx
apps/app/src/app/panel/[panel]/components/WorklistTable.tsx
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/app/panel/[panel]/view/[view]/page.tsx
apps/app/src/hooks/use-column-creator.ts
apps/app/src/hooks/use-medplum-store.ts
apps/app/src/hooks/use-panel-store.ts
apps/app/src/hooks/use-search.ts
apps/app/src/lib/fhir-path.test.ts
apps/app/src/lib/fhir-path.ts
apps/app/src/lib/medplum.ts
apps/app/src/lib/utils.ts
apps/app/src/types/worklist.ts

Add column reordering by drag-and-drop. Add column visibility and columns menu

feat: 🎸 columns management

---

apps/app/src/app/panel/[panel]/components/WorklistNavigation.tsx
apps/app/src/app/panel/[panel]/components/WorklistTable.tsx
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/app/panel/[panel]/view/[view]/page.tsx
apps/app/src/hooks/use-medplum-store.ts
apps/app/src/lib/medplum.ts

reduce dependency on medplum while loading the page, load medplum data in parallel, still needs improvements

fix: 🐛 improve page load performance

---

SEARCH_FEATURE_PROPOSAL.md
SEARCH_FEATURE_README.md
apps/app/src/app/panel/[panel]/components/PatientDetails.tsx
apps/app/src/app/panel/[panel]/components/SearchableAdditionalInfo.tsx
apps/app/src/app/panel/[panel]/components/SearchableExtensionDetails.tsx
apps/app/src/app/panel/[panel]/components/TaskDetails.tsx
apps/app/src/components/SearchableKeyValueSection.tsx
apps/app/src/hooks/useKeyValueSearch.ts
apps/app/src/utils/featureFlags.ts

- drawer now has a search box where user can search by key, value, both
- drawer shows only results after search
- drawer show collapsible sections for metadata

Pla 341 task key value search in context drawer

---

apps/app/src/app/panel/[panel]/components/WorklistFooter.tsx
apps/app/src/app/panel/[panel]/components/WorklistNavigation.tsx
apps/app/src/app/panel/[panel]/components/WorklistTable.tsx
apps/app/src/app/panel/[panel]/components/WorklistToolbar.tsx
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/app/panel/[panel]/view/[view]/page.tsx

- Make the footer and the toolbar sticky. 
- The Drawer doesn't mess with the layout. 
- Actions are all together close the search text box
- Add a delete button to tabs that is always visible. Fix the Search bar

Pla 344 UI fixes actions shell

---

.vscode/settings.json
apps/app/package.json
apps/services/package.json
apps/services/src/model/migrations/wl-ddl_20250616104328.ts
apps/services/src/model/orm.config.ts
apps/services/src/modules/column/entities/base-column.entity.ts
apps/services/src/modules/column/entities/calculated-column.entity.ts
apps/services/src/modules/column/routes/column-create-base.ts
apps/services/src/modules/column/routes/column-create-calculated.ts
apps/services/src/modules/column/routes/column-list.ts
apps/services/src/modules/column/routes/column-update.ts
apps/services/src/server.ts
apps/services/tsconfig.json
dev/api-tests/environments/Local.bru
package.json
packages/types/package.json
packages/types/src/columns.ts
pnpm-lock.yaml

- Columns now have tags to filter and group columns by meaning, purpose, or whatever
- Tags are available for create/update/list endpoints
- Columns (Base|Calculated) entities now have the tags as a JSON string array, optional

feat: 🎸 columns

---

apps/app/src/app/(home)/components/PanelsTable.tsx
apps/app/src/app/(home)/page.tsx
apps/app/src/app/panel/[panel]/components/ColumnsDropdown.tsx
apps/app/src/app/panel/[panel]/components/WorklistToolbar.tsx
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/app/panel/[panel]/view/[view]/page.tsx
apps/app/src/hooks/use-panel-store.tsx
apps/app/src/lib/medplum.ts
apps/app/src/lib/storage/api-storage-adapter.ts
apps/app/src/lib/storage/type-adapters.ts
apps/services/src/modules/column/routes/column-list.ts

fix visibility toggle, fix panel creation to avoid race condition and
duplicated creation, fix llm column creation, fix sorting for columns, improve reliability of queries, fix cache issues related with panels, views and columns

fix: 🐛 fix several bugs on UI

---

apps/app/src/app/panel/[panel]/components/WorklistTable.tsx
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/app/panel/[panel]/view/[view]/page.tsx

we can now apply sort to any column type

feat: 🎸 perform fhir sorting on all columns

---

apps/app/src/api/panelsAPI.ts
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/lib/storage/api-storage-adapter.ts
apps/app/src/lib/storage/type-adapters.ts
apps/services/src/model/migrations/wl-ddl_20250617101205.ts
apps/services/src/model/resource.entity.ts
apps/services/src/modules/panel/entities/panel.entity.ts
apps/services/src/modules/panel/routes/panel-create.ts
apps/services/src/modules/panel/routes/panel-get.ts
apps/services/src/modules/panel/routes/panel-list.ts
apps/services/src/modules/panel/routes/panel-update.ts
apps/services/src/modules/view/entities/view.entity.ts
packages/types/src/panels.ts

Fix Panel filters, now Filter are stored for Panels as well

fix: 🐛 panels

---

apps/app/src/app/panel/[panel]/components/WorklistTable.tsx
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/app/panel/[panel]/view/[view]/page.tsx
apps/app/src/lib/storage/api-storage-adapter.ts
apps/app/src/lib/storage/type-adapters.ts
apps/app/src/types/worklist.ts
apps/services/dockerfile
apps/services/src/modules/view/routes/view-delete.ts

- Inherit sort rules when creating a new view
- Persist the sort rules so user can see them everytime they open the view

feat: 🎸 store column sort rules at the view level

---

apps/app/src/app/panel/[panel]/components/SearchableExtensionDetails.tsx
apps/app/src/components/JsonViewer/JsonRawMode.tsx
apps/app/src/components/JsonViewer/JsonToggle.tsx
apps/app/src/components/JsonViewer/JsonViewMode.tsx
apps/app/src/components/JsonViewer/JsonViewer.tsx
apps/app/src/components/JsonViewer/index.ts
apps/app/src/components/JsonViewer/types.ts
apps/app/src/components/SearchableKeyValueSection.tsx

Add JsonViewer in the right drawer to show objects and json strings using a better and structured viewer

feat: 🎸 json viewer

---

apps/app/src/app/panel/[panel]/components/WorklistColumnMenu.tsx

Updated column's menu items order

feat: 🎸 column(s)

---

.github/workflows/ci.yml
turbo.json

Fix typecheck script pipeline to have build as dependendcy

chore: 🤖 pipelines

---

apps/app/src/hooks/use-authentication.tsx
apps/app/src/lib/config.ts

stytch is currently being used to store the medplum client, while we have it we need to support multiple environments

feat: 🎸 make stytch config fetch secrets depending on env

---

apps/app/src/app/panel/[panel]/components/TaskDetails.tsx

**What we are doing?**
Changing [Available Connectors -> open as a link] to [Complete in ...] for tasks in the right drawer
Why?
Because the thing is properly an action to complete into not a link to a connector

style: 💄 task actions

---

apps/app/src/app/panel/[panel]/components/PatientContext.tsx
apps/app/src/app/panel/[panel]/components/TaskDetails.tsx

**What we are doing?**
Add a summary section for patient and task details to render the latest AI Summary from the care flow
**Why?**
To make it clearer and usable for the user to see the content, using well-rendered content

feat: 🎸 summary

---

apps/app/src/app/panel/[panel]/components/WorklistColumnMenu.tsx
apps/app/src/app/panel/[panel]/components/WorklistNavigation.tsx
apps/app/src/app/panel/[panel]/components/WorklistSortableColumnHeader.tsx
apps/app/src/app/panel/[panel]/components/WorklistTable.tsx
apps/app/src/app/panel/[panel]/components/WorklistTableRow.tsx
apps/app/src/app/panel/[panel]/page-reactive.tsx
apps/app/src/components/ConfirmDeleteModal.tsx
apps/app/src/components/DateTimeFormatSelector.tsx
apps/app/src/contexts/medplum-context.tsx
apps/app/src/hooks/use-reactive-panel-store.tsx
apps/app/src/lib/medplum.ts

This PR implements performance optimizations focused on making user interactions feel near-instant by introducing optimistic updates and UI improvements across key workflows.
- Optimistic Updates: Implemented optimistic response pattern for task assignment/unassignment operations
- Enhanced UX: Added visual hints to help users understand that clicking on assignees will unassign or reassign tasks
- Reduced Latency: Users now see immediate feedback when assigning/unassigning tasks without waiting for server responses
-  Optimistic Column Updates: Column modifications now use optimistic responses for immediate UI feedback
- Improved Menu Interactions: Added mechanism to properly close sortable column menus
- Enhanced Filtering: Implemented partial match filtering for better search experience …

Pla-374-interactions-that-should-feel-near-instant

---

apps/app/src/app/panel/[panel]/components/WorklistVirtualizedTable/StickyContext.tsx
apps/app/src/app/panel/[panel]/components/WorklistVirtualizedTable/StickyHeader.tsx
apps/app/src/app/panel/[panel]/components/WorklistVirtualizedTable/VirtualizedCell.tsx
apps/app/src/app/panel/[panel]/components/WorklistVirtualizedTable/VirtualizedWorklistTable.tsx

- use fhir helper to show nested path in cell rendering
- use row level styling for the hover state
- get rid of auto expanding columns to keep column dimensions stable

fix: ui bugs in the new virtualised table

---

apps/app/src/api/panelsAPI.ts
apps/app/src/app/actions/ai-chat.ts
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/app/panel/[panel]/view/[view]/page.tsx
apps/app/src/hooks/use-column-creator.ts
apps/app/src/hooks/use-reactive-panel-store.tsx
apps/app/src/lib/column-utils.ts
apps/app/src/lib/storage/api-storage-adapter.ts
apps/app/src/lib/storage/local-storage-adapter.ts
apps/app/src/lib/storage/reactive-storage-adapter.ts
apps/app/src/lib/storage/types.ts
apps/app/src/types/worklist.ts

- Update StorageAdapter interface to return ID mappings from updatePanel
- Enhance API storage adapter to capture database IDs from column creation
- Add ID correction logic in reactive panel store to update client state
- Apply corrected IDs to both panel columns and view references
- Replace console logging with structured logger
- Ensure subsequent column operations work with correct database IDs
Fixes issue where AI-generated columns with temporary IDs would disappear
after page refresh due to ID mismatch between client and database.

Pla-442-bug-column-agent-is-not-reliable-enough

---

apps/docs/.vitepress/config.mts
apps/docs/.vitepress/theme/index.ts
apps/docs/.vitepress/theme/style.css
apps/docs/explanation/data-flow/application-startup.md
apps/docs/explanation/data-flow/authentication-flow.md
apps/docs/explanation/data-flow/index.md
apps/docs/explanation/data-flow/panel-entry-flow.md
apps/docs/explanation/data-flow/real-time-updates.md
apps/docs/explanation/data-flow/state-management.md
apps/docs/package.json
package.json
pnpm-lock.yaml

Update documentation to include data flows:
- Main page introducing the flows [http://localhost:8073/panels/explanation/data-flow/](http://localhost:8073/panels/explanation/data-flow/)
- Application startup flow [http://localhost:8073/panels/explanation/data-flow/application-startup](http://localhost:8073/panels/explanation/data-flow/application-startup)
- Panel entry flow [http://localhost:8073/panels/explanation/data-flow/panel-entry-flow](http://localhost:8073/panels/explanation/data-flow/panel-entry-flow)
- Realtime update flow [http://localhost:8073/panels/explanation/data-flow/real-time-updates](http://localhost:8073/panels/explanation/data-flow/real-time-updates)
- Authentication flow [http://localhost:8073/panels/explanation/data-flow/authentication-flow](http://localhost:8073/pane …

docs: ✏️ flows

---

apps/app/src/app/panel/[panel]/components/ModalDetails/FramePanel.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/ModalDetails.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/TaskDetails/TaskDetails.tsx

[PLA-462] Added AHP header with name & status

---

apps/app/src/app/actions/ai-chat.ts
apps/app/src/app/panel/[panel]/page.tsx
apps/app/src/app/panel/[panel]/view/[view]/page.tsx
apps/app/src/components/AIConversationDrawer.tsx
apps/app/src/components/AppShell.tsx
apps/app/src/components/Providers.tsx
apps/app/src/components/RightDrawer.tsx
apps/app/src/components/Toast.tsx
apps/app/src/components/ToastContainer.tsx
apps/app/src/contexts/DrawerContext.tsx
apps/app/src/contexts/ToastContext.tsx
apps/app/src/hooks/use-column-creator.ts
apps/app/src/hooks/use-column-operations.ts

- Updated DrawerContext to support dynamic component pattern with component + props
- Modified RightDrawer to render components dynamically with fresh props
- Updated AppShell to use new drawer pattern without children
- Wrapped handleSendMessage in useCallback with proper dependencies in useColumnCreator
- Fixed drawer props memoization to ensure agent always has current context
- Preserves conversation history while updating context during navigation
Fixes issue where column agent would use stale context when users navigated
between views or changed view types, leading to columns being added to wrong views.

fix: column agent context refresh issue when navigating views

---

.husky/pre-commit
apps/app/src/app/(home)/error.tsx

- error boundary automatically logs error to the backend to help
with troubleshooting

feat: add error boundary to catch any rendering error

---

packages/bots/src/bots/awellhealth/patient.ts

- Add patient.ts bot to handle patient.created, patient.updated, and patient.deleted webhooks
- Implement FHIR Patient resource creation/update/deletion with proper mapping
- Add safeStringTrim utility function to handle type-safe string processing
- Support both string and numerical sex values (ISO/IEC 5218 standard)
- Include multi-identifier patient search for create/update operations
- Add hard delete functionality for patient.deleted events
- Comprehensive error handling and logging throughout

Create patient webhook bot with FHIR patient resource management

---

apps/app/src/app/panel/[panel]/components/ModalDetails/PatientDetails/PatientData.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/WaypointContent/WaypointContent.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/TaskDetails/TaskComments.tsx
packages/bots/src/bots/awellhealth/activity-to-task.ts
packages/bots/src/bots/awellhealth/patient.ts

- Fix typos
- Add phone number use from fhir
- Improve patient delete bot, it should also delete patient tasks
- Improve patient creation bot to include use = home for the normal phone number
- Improve timeline by only showing that a task is completed when it is actually completed

[PLA-498] Minor improvements

---

apps/app/src/app/panel/[panel]/components/ModalDetails/ModalDetails.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/CardRowItem.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/RenderValue.tsx
apps/app/src/app/panel/[panel]/components/VirtualizedTable/cells/DateCell.tsx
apps/app/src/hooks/use-date-time-format.test.tsx
apps/app/src/hooks/use-date-time-format.tsx

- Replace formatDateIgnoringTimeZone with proper timezone-agnostic formatDate function
- Consolidate date parsing logic using shared parseDate helper
- Make both formatDate and formatDateTime use consistent patterns with date-fns
- Update DateCell and ModalDetails to use new formatDate for date-only values
- Simplify RenderValue by removing dateContext prop anti-pattern
- Move date formatting decisions to parent components with proper context
- Add comprehensive tests for both formatting functions
This eliminates multiple recurring date formatting bugs by ensuring all date
handling uses battle-tested date-fns library with consistent patterns.

Refactor date formatting to eliminate inconsistencies and duplication

---

packages/bots/src/bots/awellhealth/patient.ts

- Replace separate create/update logic with atomic upsert operations
- Use medplum.upsertResource() to handle both patient creation and updates
- Eliminate race conditions when webhooks arrive in quick succession
- Simplify handlePatientCreated and handlePatientUpdated to use shared upsertPatient function
Resolves issue where duplicate patients were created when webhooks were received simultaneously or in quick succession.

fix: prevent duplicate patients by using upsert operations

---

apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/CardRowItem.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/ContentCards/ContentCards.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/FhirExpandableCard.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/HighlightContent.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/RenderValue.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/RenderWithCopy.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/SearchInput.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/StaticContent.tsx
apps/app/src/app/panel/[panel]/components/ModalDetails/StaticContent/utils.ts
apps/app/src/hooks/use-debounce.ts
apps/app/src/hooks/use-search.ts

**Type Safety & Architecture:**
- Replace dangerous  casts with safer type checking
- Add comprehensive TypeScript interfaces (RenderableValue, RenderableObject, TableRow)
- Remove all  types and replace with proper type definitions
- Move useDebounce hook from utils.ts to dedicated hooks/use-debounce.ts file
- Co-locate types with RenderValue component for better discoverability
**Error Handling & Robustness:**
- Add centralized handleError utility with contextual logging
- Wrap potentially failing operations in try-catch blocks
- Add proper null checks and type guards throughout
- Improve Bundle creation with individual resource validation
- Handle Promise.allSettled results with proper error checking
**Search & UX Improvements:**
- Replace hasSearchQuery with createSearchFilter utility …

refactor: improve type safety and code quality in StaticContent components

---

.cursor/rules/bot-best-practices.mdc
packages/bots/src/bots/awellhealth/activity-to-task.ts
packages/bots/src/bots/awellhealth/clinical-note-to-composition.ts
packages/bots/src/bots/awellhealth/datapoint-bot-router.ts
packages/bots/src/bots/awellhealth/datapoint-to-encounter.ts
packages/bots/src/bots/awellhealth/datapoint-to-observation.ts
packages/bots/src/bots/awellhealth/elation-connectors.ts
packages/bots/src/bots/awellhealth/patient.ts
packages/bots/src/bots/awellhealth/task-enrichment.ts
packages/bots/src/bots/utility_functions.ts

- new cursor rule that describes best practices
- add documentation to all existing bots

feat(cursor): document best practices for bot development
